init:
- git config --global core.autocrlf true
branches:
  only:
  - master
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
build_script:
- ps: .\run.ps1 -CI default-build
clone_depth: 1
test: 'off'
deploy: 'off'
image: Visual Studio 2017
