language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libunwind8
mono: none
os:
- linux
- osx
osx_image: xcode8.2
branches:
  only:
  - master
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
before_install:
- if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  /usr/local/lib/; fi
script:
- ./build.sh --ci
