language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; brew install openssl; brew link --force openssl; fi
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh --quiet verify
env:
  - KOREBUILD_TEST_SKIPMONO=1