// <auto-generated />
namespace Resources
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class HomeController.fr
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Resources.HomeController.fr", typeof(HomeController.fr).GetTypeInfo().Assembly);

        /// <summary>
        /// Bonjour!
        /// </summary>
        internal static string Hello there!!
        {
            get { return GetString("Hello there!!"); }
        }

        /// <summary>
        /// Bonjour!
        /// </summary>
        internal static string FormatHello there!!()
        {
            return GetString("Hello there!!");
        }

        /// <summary>
        /// Apprenez à créer des applications ASP.NET qui peuvent fonctionner ne importe où.
        /// </summary>
        internal static string Learn how to build ASP.NET apps that can run anywhere.
        {
            get { return GetString("Learn how to build ASP.NET apps that can run anywhere."); }
        }

        /// <summary>
        /// Apprenez à créer des applications ASP.NET qui peuvent fonctionner ne importe où.
        /// </summary>
        internal static string FormatLearn how to build ASP.NET apps that can run anywhere.()
        {
            return GetString("Learn how to build ASP.NET apps that can run anywhere.");
        }

        /// <summary>
        /// apprendre Encore Plus
        /// </summary>
        internal static string Learn More
        {
            get { return GetString("Learn More"); }
        }

        /// <summary>
        /// apprendre Encore Plus
        /// </summary>
        internal static string FormatLearn More()
        {
            return GetString("Learn More");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
