// <auto-generated />
namespace Resources
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Views.Shared._LocalizationLayout.cshtml.fr
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Resources.Views.Shared._LocalizationLayout.cshtml.fr", typeof(Views.Shared._LocalizationLayout.cshtml.fr).GetTypeInfo().Assembly);

        /// <summary>
        /// sur
        /// </summary>
        internal static string About
        {
            get { return GetString("About"); }
        }

        /// <summary>
        /// sur
        /// </summary>
        internal static string FormatAbout()
        {
            return GetString("About");
        }

        /// <summary>
        /// Nom de l'application
        /// </summary>
        internal static string Application name
        {
            get { return GetString("Application name"); }
        }

        /// <summary>
        /// Nom de l'application
        /// </summary>
        internal static string FormatApplication name()
        {
            return GetString("Application name");
        }

        /// <summary>
        /// communiquer
        /// </summary>
        internal static string Contact
        {
            get { return GetString("Contact"); }
        }

        /// <summary>
        /// communiquer
        /// </summary>
        internal static string FormatContact()
        {
            return GetString("Contact");
        }

        /// <summary>
        /// maison
        /// </summary>
        internal static string Home
        {
            get { return GetString("Home"); }
        }

        /// <summary>
        /// maison
        /// </summary>
        internal static string FormatHome()
        {
            return GetString("Home");
        }

        /// <summary>
        /// Mon application ASP.NET
        /// </summary>
        internal static string My ASP.NET Application
        {
            get { return GetString("My ASP.NET Application"); }
        }

        /// <summary>
        /// Mon application ASP.NET
        /// </summary>
        internal static string FormatMy ASP.NET Application()
        {
            return GetString("My ASP.NET Application");
        }

        /// <summary>
        /// Ressources pour ce point de vue
        /// </summary>
        internal static string Resources for this view
        {
            get { return GetString("Resources for this view"); }
        }

        /// <summary>
        /// Ressources pour ce point de vue
        /// </summary>
        internal static string FormatResources for this view()
        {
            return GetString("Resources for this view");
        }

        /// <summary>
        /// Aujourd'hui, ce est: {0}
        /// </summary>
        internal static string Today is: {0}
        {
            get { return GetString("Today is: {0}"); }
        }

        /// <summary>
        /// Aujourd'hui, ce est: {0}
        /// </summary>
        internal static string FormatToday is: {0}(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("Today is: {0}"), p0);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
