// <auto-generated />
namespace Resources
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Views.Home.Locpage.cshtml.en-GB
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Resources.Views.Home.Locpage.cshtml.en-GB", typeof(Views.Home.Locpage.cshtml.en-GB).GetTypeInfo().Assembly);

        /// <summary>
        /// Hello there!!
        /// </summary>
        internal static string Hello there!!
        {
            get { return GetString("Hello there!!"); }
        }

        /// <summary>
        /// Hello there!!
        /// </summary>
        internal static string FormatHello there!!()
        {
            return GetString("Hello there!!");
        }

        /// <summary>
        /// Learn how to build ASP.NET apps that can run anywhere.
        /// </summary>
        internal static string Learn how to build ASP.NET apps that can run anywhere.
        {
            get { return GetString("Learn how to build ASP.NET apps that can run anywhere."); }
        }

        /// <summary>
        /// Learn how to build ASP.NET apps that can run anywhere.
        /// </summary>
        internal static string FormatLearn how to build ASP.NET apps that can run anywhere.()
        {
            return GetString("Learn how to build ASP.NET apps that can run anywhere.");
        }

        /// <summary>
        /// Learn More
        /// </summary>
        internal static string Learn More
        {
            get { return GetString("Learn More"); }
        }

        /// <summary>
        /// Learn More
        /// </summary>
        internal static string FormatLearn More()
        {
            return GetString("Learn More");
        }

        /// <summary>
        /// Hi {0,-10}! You are in {1:yyyy} year and today is {2}
        /// </summary>
        internal static string Hi
        {
            get { return GetString("Hi"); }
        }

        /// <summary>
        /// Hi {0,-10}! You are in {1:yyyy} year and today is {2}
        /// </summary>
        internal static string FormatHi(object p2)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("Hi"), p2);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
