// Copyright (c) Microsoft Open Technologies, Inc. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;

namespace Microsoft.AspNet.Mvc.Rendering
{
    /// <summary>
    /// Specifies the contracts for caching view locations generated by <see cref="IViewLocationExpander"/>.
    /// </summary>
    public interface IViewLocationCache
    {
        /// <summary>
        /// Gets a cached view location based on the specified <paramref name="values"/>.
        /// </summary>
        /// <param name="values">A <see cref="SortedDictionary{TKey, TValue}"/> that is used to compute the key for
        /// the lookup.
        /// <returns>An instance of <see cref="ViewLocationCacheResult"/> that contains the computed key and 
        /// a value if available.</returns>
        ViewLocationCacheResult Get(SortedDictionary<string, string> values);

        /// <summary>
        /// Sets the cached view location for the specified <paramref name="key"/>.
        /// </summary>
        /// <param name="key">The key for the cache lookup.</param>
        /// <param name="value">The view location.</param>
        void Set(string key, string value);
    }
}