//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.Mvc.RazorPages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNetCore.Mvc.RazorPages.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Page created by &apos;{0}&apos; must be an instance of &apos;{1}&apos;..
        /// </summary>
        public static string ActivatedInstance_MustBeAnInstanceOf {
            get {
                return ResourceManager.GetString("ActivatedInstance_MustBeAnInstanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The @page directive for the Razor page at {0} cannot override the relative path prefix..
        /// </summary>
        public static string PageActionDescriptorProvider_RouteTemplateCannotBeOverrideable {
            get {
                return ResourceManager.GetString("PageActionDescriptorProvider_RouteTemplateCannotBeOverrideable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The &apos;{0}&apos; property of &apos;{1}&apos; must not be null..
        /// </summary>
        public static string PropertyOfTypeCannotBeNull {
            get {
                return ResourceManager.GetString("PropertyOfTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Path must begin with a forward slash &apos;/&apos;..
        /// </summary>
        public static string RazorProject_PathMustStartWithForwardSlash {
            get {
                return ResourceManager.GetString("RazorProject_PathMustStartWithForwardSlash", resourceCulture);
            }
        }
    }
}
