// Copyright (c) Microsoft Open Technologies, Inc. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;

namespace Microsoft.AspNet.Mvc.Rendering
{
    /// <summary>
    /// Specifies the contracts for caching view locations generated by <see cref="IViewLocationExpander"/>.
    /// </summary>
    public interface IViewLocationCache
    {
        /// <summary>
        /// Gets a cached view location based on the specified <paramref name="context"/>.
        /// </summary>
        /// <param name="context">The <see cref="ViewLocationExpanderContext"/> for the current view location 
        /// expansion.</param>
        /// <returns>A <see cref="ViewLocationCacheResult"/> that contains the cached location, if available.</returns>
        ViewLocationCacheResult Get(ViewLocationExpanderContext context);

        /// <summary>
        /// Adds a cache entry for the specified <paramref name="key"/>.
        /// </summary>
        /// <param name="key">The cache key</param>.
        /// <param name="value">The view location that is to be cached.</param>
        void Set(string key, string value);
    }
}