//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.Mvc.Razor {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNetCore.Mvc.Razor.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to One or more compilation failures occurred:.
        /// </summary>
        internal static string CompilationFailed {
            get {
                return ResourceManager.GetString("CompilationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unexpected return value from &apos;{1}.{2}&apos; for URL &apos;{0}&apos;. If the &apos;{1}&apos; service has been overridden, change &apos;{2}&apos; to replace only the &apos;~/&apos; prefix. Otherwise, add the following directive to the Razor page to disable URL resolution relative to the application&apos;s &apos;webroot&apos; setting:
        ///
        ///@{3} &quot;{4}, {5}&quot;.
        /// </summary>
        internal static string CouldNotResolveApplicationRelativeUrl_TagHelper {
            get {
                return ResourceManager.GetString("CouldNotResolveApplicationRelativeUrl_TagHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; cannot be invoked when a Layout page is set to be executed..
        /// </summary>
        internal static string FlushPointCannotBeInvoked {
            get {
                return ResourceManager.GetString("FlushPointCannotBeInvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generated Code.
        /// </summary>
        internal static string GeneratedCodeFileName {
            get {
                return ResourceManager.GetString("GeneratedCodeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} returned by &apos;{1}&apos; must be an instance of &apos;{2}&apos;..
        /// </summary>
        internal static string Instrumentation_WriterMustBeBufferedTextWriter {
            get {
                return ResourceManager.GetString("Instrumentation_WriterMustBeBufferedTextWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The layout view &apos;{0}&apos; could not be located. The following locations were searched:{1}.
        /// </summary>
        internal static string LayoutCannotBeLocated {
            get {
                return ResourceManager.GetString("LayoutCannotBeLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Layout page &apos;{0}&apos; cannot be rendered after &apos;{1}&apos; has been invoked..
        /// </summary>
        internal static string LayoutCannotBeRendered {
            get {
                return ResourceManager.GetString("LayoutCannotBeRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A circular layout reference was detected when rendering &apos;{0}&apos;. The layout page &apos;{1}&apos; has already been rendered..
        /// </summary>
        internal static string LayoutHasCircularReference {
            get {
                return ResourceManager.GetString("LayoutHasCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The &apos;inherits&apos; keyword is not allowed when a &apos;{0}&apos; keyword is used..
        /// </summary>
        internal static string MvcRazorCodeParser_CannotHaveModelAndInheritsKeyword {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_CannotHaveModelAndInheritsKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The &apos;{0}&apos; keyword must be followed by a type name on the same line..
        /// </summary>
        internal static string MvcRazorCodeParser_ModelKeywordMustBeFollowedByTypeName {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_ModelKeywordMustBeFollowedByTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Only one &apos;{0}&apos; statement is allowed in a file..
        /// </summary>
        internal static string MvcRazorCodeParser_OnlyOneModelStatementIsAllowed {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_OnlyOneModelStatementIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The resource &apos;{0}&apos; specified by &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string RazorFileInfoCollection_ResourceCouldNotBeFound {
            get {
                return ResourceManager.GetString("RazorFileInfoCollection_ResourceCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unsupported hash algorithm..
        /// </summary>
        internal static string RazorHash_UnsupportedHashAlgorithm {
            get {
                return ResourceManager.GetString("RazorHash_UnsupportedHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} operation cannot be performed while inside a writing scope in &apos;{1}&apos;..
        /// </summary>
        internal static string RazorPage_CannotFlushWhileInAWritingScope {
            get {
                return ResourceManager.GetString("RazorPage_CannotFlushWhileInAWritingScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to perform &apos;{0}&apos; assignment. Tag helper property &apos;{1}.{2}&apos; must not be null..
        /// </summary>
        internal static string RazorPage_InvalidTagHelperIndexerAssignment {
            get {
                return ResourceManager.GetString("RazorPage_InvalidTagHelperIndexerAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} invocation in &apos;{1}&apos; is invalid. {0} can only be called from a layout page..
        /// </summary>
        internal static string RazorPage_MethodCannotBeCalled {
            get {
                return ResourceManager.GetString("RazorPage_MethodCannotBeCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} was unable to provide metadata for expression &apos;{1}&apos;..
        /// </summary>
        internal static string RazorPage_NullModelMetadata {
            get {
                return ResourceManager.GetString("RazorPage_NullModelMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There is no active writing scope to end..
        /// </summary>
        internal static string RazorPage_ThereIsNoActiveWritingScopeToEnd {
            get {
                return ResourceManager.GetString("RazorPage_ThereIsNoActiveWritingScopeToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} has not been called for the page at &apos;{1}&apos;. To ignore call {2}()..
        /// </summary>
        internal static string RenderBodyNotCalled {
            get {
                return ResourceManager.GetString("RenderBodyNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Section &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string SectionAlreadyDefined {
            get {
                return ResourceManager.GetString("SectionAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} invocation in &apos;{1}&apos; is invalid. The section &apos;{2}&apos; has already been rendered..
        /// </summary>
        internal static string SectionAlreadyRendered {
            get {
                return ResourceManager.GetString("SectionAlreadyRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Section &apos;{0}&apos; is not defined in path &apos;{1}&apos;..
        /// </summary>
        internal static string SectionNotDefined {
            get {
                return ResourceManager.GetString("SectionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following sections have been defined but have not been rendered by the page at &apos;{0}&apos;: &apos;{1}&apos;. To ignore an unrendered section call {2}(&quot;sectionName&quot;)..
        /// </summary>
        internal static string SectionsNotRendered {
            get {
                return ResourceManager.GetString("SectionsNotRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to View of type &apos;{0}&apos; cannot be activated by &apos;{1}&apos;..
        /// </summary>
        internal static string ViewCannotBeActivated {
            get {
                return ResourceManager.GetString("ViewCannotBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0} must be set to access &apos;{1}&apos;..
        /// </summary>
        internal static string ViewContextMustBeSet {
            get {
                return ResourceManager.GetString("ViewContextMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; must be a {1} that is generated as result of the call to &apos;{2}&apos;..
        /// </summary>
        internal static string ViewLocationCache_KeyMustBeString {
            get {
                return ResourceManager.GetString("ViewLocationCache_KeyMustBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The &apos;{0}&apos; method must be called before &apos;{1}&apos; can be invoked..
        /// </summary>
        internal static string ViewMustBeContextualized {
            get {
                return ResourceManager.GetString("ViewMustBeContextualized", resourceCulture);
            }
        }
    }
}
